name: school_app_mvp
description: MVP of school app
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  http: ^1.2.2
  shared_preferences: ^2.1.0
  flutter_svg: ^1.1.0
  syncfusion_flutter_pdfviewer: ^31.1.21
  assets:
    - assets/images/"dashbaoard_image.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/"dashbaoard_image.png"
